name: ci-dev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.5

      - name: Setup node v16
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint project
        run: pnpm lint

      - name: Test project
        run: pnpm test

      - name: Generate coverage
        uses: codecov/codecov-action@v2

      - name: Build project
        run: pnpm build

      # - name: Release Edge version
      #   if: github.event_name == 'push'
      #   run: ./scripts/release-edge.sh
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
