name: ci-main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.5

      - name: Setup node v16
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint project
        run: pnpm lint

      - name: Test project
        run: pnpm test

      - name: Generate coverage
        uses: codecov/codecov-action@v2

      - name: Build project
        run: pnpm build

      - name: Check if the version has been bumped
        id: check
        uses: EndBug/version-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Release Main version
      #   if: github.event_name == 'push' && steps.check.outputs.changed == 'true'
      #   run: ./scripts/release.sh
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
